# this is second task of OS

name: 'rania walid'

on:
  push:
    branches:
      - master


jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: "Print the path"
        run: pwd
      - name: "Print name"
        run: echo rania
      - name: "Before Add Action"
        run: ls
      - uses: actions/checkout@v3
      - name: "After Add Action"
        run: ls -a
      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.USERNAME_TOKEN }} --password ${{ secrets.PASSWORD_TOKEN }}
      - name: " build image "
        run: docker build -t ${{ secrets.USERNAME_TOKEN}}/docker-my_second_image .
      - name: " push image"
        run: docker push ${{ secrets.USERNAME_TOKEN}}/docker-my_second_image



